### PR TITLE
Add Refill levels of detail and label steps

### PR DESCRIPTION
**Pull request by sensescape**
Docs docs docs

- [x] Version 7 to 8
- [x] Add `color-` prefix on earlier color theme examples
- [x] Draft _text_ for **detail** themes
- [x] Final _text_ for **detail** themes
- [x] Draft _images_ for **detail** themes
- [x] Final _images_ for **detail** themes
- [x] Draft _text_ for **label** themes
- [x] Final _text_ for **label** themes
- [x] Draft _images_ for **label** themes
- [x] Final _images_ for **label** themes
- [x] Move final images for all to this dir, and redo the paths
- [x] Note v8 doesn't support `no-labels` and `more-labels` as standalone style variants now, use theme imports instead. (Bug with Tangram ZIP bundle support.)

### CODE REVIEW

**Comment by kkowalsky** [comment]
- None of the images are showing up 

- the color themes are going to have "color-color-type.zip" at the end of their names, make sure you update

**Comment by kkowalsky** [comment]
the 3 mallorca images still are 404ing for me, but then all is good!

**Comment by nvkelso** [comment]
@kkowalsky fixed `color-` in https://github.com/tangrams/cartography-docs/pull/31/commits/af7718f208ca208babc4ac50b7124bcf61998daf. Good catch!

**Comment by nvkelso** [comment]
@kkowalsky It's because of how precog and final publish to mapzen.com corrupt relative links :\ 

The images do appear correctly when finally published to mapzen.com:

- https://mapzen.com/documentation/cartography/themes/#refill

And since we're not changing them in this PR, they'll continue showing up.

We need to move the remote images for **detail** and **label** into this repo as well, and then they'll look like they will 404, too. But will be fine on final publish. _shrug_

**Comment by kkowalsky** [comment]
okay just double checking!

**Review by kkowalsky — APPROVED** [review]

**Review by nvkelso — APPROVED** [review]

**Pull request merged**
